### ISSUE TITLE
FOUND UNSUPPORTED LINE OBJECT

### ISSUE THREAD

**Issue by ghost** [andrewhodel/dxfToMillcrum#1]
Now begins the pain that no one else felt like doing (why they refuse to like DXFs) (:

I uploaded a worst case scenario for you to https://drive.google.com/file/d/0B-UxBll2MapjcGo2TmN5LU5Ra1k/view?usp=sharing

That was drawn in Sketchup, exported to DXF with the Guitarlist plugin, then edited in QCad and saved as DXF R15 (Autocad 2000) 

(:

.....

FOUND UNSUPPORTED LINE OBJECT

Traceback (most recent call last):
  File "c:\dxftomillcrum\dxfToMillcrum.py", line 404, in <module>
    process(sys.argv[1])
  File "c:\dxftomillcrum\dxfToMillcrum.py", line 388, in process
    totalX = maxX-minX
NameError: global name 'maxX' is not defined

C:\dxftomillcrum>

**Comment by andrewhodel** [comment]
It only supports polylines, not lines.  Adding line support would be a feature request not a bug.
Anytime you are using a DXF file you can easily change everything to a path instead of lines or circles and it will do what it is supposed to.

There's no point in supporting lines, because how do you define the inside or outside of a line for a toolpath?

**Comment by ghost** [comment]
Resolved.  Converted to polylines and works ok now:

![success](https://cloud.githubusercontent.com/assets/7695323/8416835/af75eaf6-1ea8-11e5-9fea-776e04f20a3c.PNG)
